version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: memcache_server_local_django
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    command: /start
