version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: memcache_server_local_django
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    command: /start

  server:
    build:
      context: .
      dockerfile: ./compose/local/mc_server/Dockerfile
    image: memcache_server_tcp
    volumes:
      - .:/app
    ports:
      - "11211:11211"
    command: python memcache_server/server/main.py database.sqlite
