# Generated by Django 2.2.5 on 2019-09-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cache', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cache',
            table='cache',
        ),
    ]
